### ISSUE TITLE
How to encode comments

### ISSUE THREAD

**Issue by tomto66** [hl7-be/hl7-be-fhir-laboratory-report#23]
We need to specify how to deal with different kinds of comments.  Here an inventory and suggestion of process:

a.	Comment on a result of analysis - may be done .note to the result?  But there are different cases possible:
a.i.	result field itself maybe comment or text (e.g. "Positive" or "No longer performed by lab; replaced by analyses XXX" 
a.ii.	Comment in commentfield may be combined with number (or comment0 in result field)

b.	Comment regd. reference values (e.g. age-specifics)  – in .text to the reference values?
c.     We often created dummy test codes to contain comments.  E.g. serum aspect.  Is this allowed? There are no LOINC codes for these dummies - will we allow every lab to use their own.  Can we use this system?  If not, how do we encode such comment?

d.    Comments regarding the laboratory (not the results). E.g. status of accreditation.  We currently use dummy tests for that.  Acceptable? If not, then how?

e.    Comments regarding tests performed by 3rd parties.  We currently do that by means of flags (codes) next to results, and use a dummy test to explain the legend.  Allowed?  If not then how?

f.    Comments regarding administrative issue, e.g. missing information like gender, DOB.  Today we use dummy test codes.  Allowed? If not, then how?

g.	There is also a .conclusionCode - to use instead of dummy analyses? Or a combination?   Dummy analysis have the advantage they can be linked to a sample (useful e.g. for serum aspect) - .conclusionCodes cannot do this. 

Do we want/need to agree on standards for the above? Or allwo every lab to do their own way?

**Comment by costateixeira** [comment]
I think we could add some narrative, but it would be better to add such use cases to our specification, and provide the example FHIR resource instances.
If we have some narrative text, we can explain the mechanism (this may be subject to interpretation)
If we list the use cases, we can make it much more concrete by examples
If we actually provide the examples, implementers will have more clarity.

**Comment by bdc-ehealth** [comment]
@tomto66 Can you provide an example for each case (testing dir in project) and add a reference here?

**Comment by tomto66** [comment]
Yes we will provide examples!

**Comment by bdc-ehealth** [comment]
comment by Alexis Van Zeveren:

•	For comments, the proper FHIR elements must be used (eg. notes), not "dummy results", either the "narrative". Tom/Macsys will try to implement this in examples.
This is issue #23 in Github. It seems this decision is not yet clearly documented in the comments.
