### ISSUE TITLE
Multilevel titles on protocols

### ISSUE THREAD

**Issue by tomto66** [hl7-be/hl7-be-fhir-laboratory-report#26]
Our laboratory reports have up to 3 levels of titles.  Here is a proposal on how to deal with these:
 
	A title is a dummy observation which is nothing but text   
	Under a title, several other observations are found with .hasMember. 
	Each such member can be either another title (sublevel) (which in only text and has members), or a lab result. 

Is this OK? If not then how? If OK, should be make this a standard?

**Comment by kjau** [comment]
Quote from the meeting minutes from the HL7 BE FHIR workgroup: https://wiki.hl7belgium.org/index.php?title=Minutes_-_Referral_WG_2020-04-19 (note: meeting was on 19-04-20**21**)

> how to link an observation to a title? 
> - within one observation you have hasMember to add member observations to create an hierarchy in your observations

**Comment by bdc-ehealth** [comment]
Is correct

**Comment by bdc-ehealth** [comment]
Decision of the workgroup:
Any parent/child relationship will be handled using the .hasMember of the Observation. There is no difference between panels/titles/subtitles
