### ISSUE TITLE
A kind of "patient status" for the specimen collection: i.e. "sitting, before vaccination, ..."

### ISSUE THREAD

**Issue by kjau** [hl7-be/hl7-be-fhir-laboratory-report#30]
Where can I code a notion that references some kind of "patient status" during collection of the specimen: sitting, lying down, standing, sober, before/after vaccination, before 1st/2nd/3rd dialysis ... (we might need more than 1 field to specify this kind of information about the patient status during collection of the specimen?).

**Comment by bdc-ehealth** [comment]
The only field I can see is specimen.note field of type Annotation.

**Comment by bdc-ehealth** [comment]
WG agrees that this is not clinically relevant, and can be put in a note : specimen.note
