### ISSUE TITLE
Text narrative in resources: obligatory for every resource?

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/hl7-be-fhir-laboratory-report#32]

**Comment by bdc-ehealth** [comment]
A text narrative is obligatory for every resource:

these are the different options of filling it: https://www.hl7.org/fhir/valueset-narrative-status.html

empty is only allowed in strict machine-to-machine interaction...

esource instances that permit narrative SHOULD always contain narrative to support human-consumption as a fallback. Structured data SHOULD NOT generally contain information of importance to human readers that is omitted from the narrative. Creators of FHIR resources should not assume that systems will render (or that humans will see) data that is not in the narrative. However, in strictly managed trading systems where all systems share a common data model and additional text is unnecessary or even a clinical safety risk, the narrative may be omitted. Implementers should give careful consideration before doing this, as it will mean that such resources can only be understood in the limited trading environment. Closed trading partner environments are very likely to open up during the lifetime of the resources they define. Also, many workflow steps involving finding and aggregating resources are much more difficult or tedious if the resources involved do not have their own text. 

https://www.hl7.org/fhir/narrative.html

**Comment by bdc-ehealth** [comment]
Decision of the workgroup:

Following the standard, there SHALL be a narrative. It can be filled using "plain text". It is not allowed to leave the narrative empty.
