### ISSUE TITLE
DiagnosticReport.Code.Coding: same as composition.type?

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/hl7-be-fhir-laboratory-report#33]
Set both to "laboratory report"?
In examples we find e.g. Hematology studies, but our reports are typically more extensive than only hematology.

**Comment by bdc-ehealth** [comment]
composition.type = "laboratory report"
diagnosticReport.code.coding = the code that fits the contents of the report best

**Comment by bdc-ehealth** [comment]
Can anapath and lab results be on the same report? To be tested. As a type we choose "Laboratory Report". 11502-2
