### ISSUE TITLE
Subtitles and panels

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/hl7-be-fhir-laboratory-report#38]
Hi,

The guidance states the following about subtitles:

>Using subtitles
>
>An important requirement is the ability to use subtitles in the structure of the laboratory report.
>
>This can be done in the report by leveraging the third way to use observations grouping supra. When doing this with the goal of only adding a subtitle, the CodeableConcept datatype of the .code element in the parent Observation will minimally contain the .text element.

So if I understand it correctly we need to add 'dummy' observations containing only the Observation.code.text field. The field is filled with the (sub)title, e.g. 'Ionen', 'Hematologie', ...

For panels, we need to do the same:
>3. The Observation may be part of a group of Observation resources. This is established by using the .hasMember in the Observation. Typically, this is used for a panel or battery where the panel code is given without a value in the parent Observation and the actual results are separate Observation resources referenced from that parent Observation.

Again we create a dummy observation to group the panel member observations. Now let's say we have a title 'Scheikunde' and a subtitle 'Ionen' and then a electrolyte panel containing (NA, K, ...). Do we have 3 dummy observations in this case? One for the title, one for the subtitle and one for the panel? Do we need a dummy observation for the panel in this case? Either way is fine by me, but I just wanted to check your opinions.

Best,
Thibault

Reference:
http://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/guidance.html

**Comment by bdc-ehealth** [comment]
I hope I understood your question correctly: If the subtitle Ionen can contain more than one panel, I would introduce a dummy observation for each panel. If it can only contain one panel, a separate observation is not necessary.

**Comment by bdc-ehealth** [comment]
Comment by Alexis Van Zeveren:

•	Similar for subtitles and "panels" (issue #38), no "dummy results" but use of FHIR concepts (e.g. hasMembers) to build hierarchies and groups,

**Comment by thibaultmh** [comment]
I am just wondering, why do we need a separate observation for the panel if we have observations for the titles?

**Comment by bdc-ehealth** [comment]
Decision from the workgroup: any parent/child relationship will be modeled using the .hasMember of the Observation. There is no difference between handling a panel or a title/subtitle
