### ISSUE TITLE
ServiceRequest references (Observation.basedOn and DiagnosticReport.basedOn)

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/hl7-be-fhir-laboratory-report#40]
Hi,

When building the diagnostic report bundle I create a ServiceRequest for the original order (containing the authoredOn, requester, order placer code, priority, ...) and ServiceRequests for the requested codes (containing request placer code, priority, ...). The first service request I store in the DiagnosticReport.basedOn. The other service requests are stored in the related Observation.basedOn. I was wondering if those latter ServiceRequests should also be stored in the DiagnosticReport.basedOn?

Best,
Thibault

**Comment by bdc-ehealth** [comment]
When reading https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/guidance.html#referencing-the-sub-order, I do not think this is necessary

**Comment by bdc-ehealth** [comment]
WG agrees.
