### ISSUE TITLE
Use of narrative

### ISSUE THREAD

**Issue by JosBellen2** [hl7-be/hl7-be-fhir-laboratory-report#45]
In the meeting on 16/11/2021 was stated  "Narrative is only for debugging, not for medical consumption".
In my opinion the narrative has the purpose to provide a system that can be easily started up and used, and can be progressively improved.
This opinion is based on the definition of Narrative ( https://www.hl7.org/fhir/narrative.html ) .
If not, how can you explain this statements in the definition of Narrative  : 

Any resource ... may include a human-readable narrative that contains a summary of the resource and **may be used 
to represent the content of the resource to a human**.

If narrative is present with a status other than 'empty', it **SHALL** reflect all content needed **for a human** **to understand the essential clinical** and business **information** for the resource.

It  SHALL be **safe** to render **only the narrative** of the resource **without** displaying any of the resource's **discrete/encoded information**

Resource instances that permit narrative **SHOULD** always **contain narrative** to support human-consumption **as a fallback**.

**Structured data SHOULD NOT generally contain** information of **importance** to **human readers** that is **omitted from the narrative**.
However, in **strictly** managed trading systems **where all systems share a common data model** and additional text is **unnecessary** or 
even a clinical safety risk, **the narrative may be omitted**. Implementers should **give careful consideration before doing this**, as 
it will mean that such resources can only be understood in the **limited trading environment.**

**Comment by tomto66** [comment]
Examples with full narrative here: https://github.com/hl7-be/hl7-be-fhir-laboratory-report/tree/master/testing/Macsys/20221119

**Comment by bdc-ehealth** [comment]
WG agrees that a narrative is mandatory, but only for "debugging" purposes, not with a clinical meaning.
