### ISSUE TITLE
Request Code 

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/hl7-be-fhir-laboratory-report#47]
Hi,

Where do we put the request codes? I propose in the ServiceRequest.code field and letting the related observations refer to the service request via the Observation.basedOn field.

An additional question, which code set do we use for the request codes? The international guidance has Snomed CT as an example, but I assume that won't cover every request code? Perhaps we should also specify an order of code sets like we did for the observations?

Best,
Thibault

**Comment by bdc-ehealth** [comment]
I propose to do the same thing as in: https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/guidance.html#guidance-for-codes-and-values-in-the-observation-resource

**Comment by tomto66** [comment]
To me that is not an issue for laboratory results; that is for requests - for me this is out of current scope!

**Comment by bdc-ehealth** [comment]
The analysis order codes from the order cannot be mapped one to one with the lab result codes from the report. So this is not relevant. This should be considered when doing the order.
