### ISSUE TITLE
At result level: accredited and / or performed by external laboratory: can we have extensions for both?

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/hl7-be-fhir-laboratory-report#48]
E.g.: testAccredited: yes/no - testPerformedByOtherLab: yes/no

**Comment by bdc-ehealth** [comment]
Is this only on the BeObservationLaboratory level, or also on the BeLaboratoryReport (DiagnosticReport)?

**Comment by LotteAd** [comment]
This would be on the Observation level.

**Comment by bdc-ehealth** [comment]
We add this unstructured in a Observation.note
