### ISSUE TITLE
At Organization-level, could there be a note-field (or other) to indicate the BELAC accreditation of the laboratory?

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/hl7-be-fhir-laboratory-report#50]
I believe this would be the appropriate place to put this information, however, the Organization resource currently does not provide any space for this information.
E.g.: "BV Centrum voor Medische Analyse is geaccrediteerd door BELAC onder certificaatnummer 007-MED."

**Comment by bdc-ehealth** [comment]
@LotteAd That is correct. Do we have to model this as a comment? Or can we consider this to be an identifier: 007-MED in the NameSystem https://economie.fgov.be/belac

**Comment by LotteAd** [comment]
I think an identifier might be a "cleaner" solution.
