### ISSUE TITLE
VALIDATOR: issue with DiagnosticReport-resource

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/hl7-be-fhir-laboratory-report#54]
I have an issue with the validator that I didn't have before. Also, earlier validated examples now generate an error when passed through the validator. The error is the following:
DiagnosticReport.identifier:DRID: minimum vereist = 1, maar gevonden 0 (uit https://www.ehealth.fgov.be/standards/fhir/StructureDefinition/be-laboratory-report)

Does anybody know anything about this? I can't seem to access the StructureDefinition for the be-laboratory-report and I cannot find any information on "DRID" on the HL7 / FHIR-website either.

**Comment by bdc-ehealth** [comment]
@LotteAd You can find more information about DRID here: https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/StructureDefinition-be-laboratory-report-definitions.html#DiagnosticReport.identifier:DRID

Can you point me to a testfile that does not validate?

**Comment by LotteAd** [comment]
Thank you!
Here you can find a Json that does not validate on this point:
https://github.com/hl7-be/hl7-be-fhir-laboratory-report/tree/master/testing/Macsys/815333051

**Comment by bdc-ehealth** [comment]
@LotteAd Validation should work now.

**Comment by LotteAd** [comment]
Works like a charm, thank you!
