### ISSUE TITLE
Naming system for BIS numbers

### ISSUE THREAD

**Issue by tomto66** [hl7-be/hl7-be-fhir-laboratory-report#59]
Needs to be created.  Could be as simple as:
"identifier":[
               {
                  "use":"official",
                  "system":"https://www.ehealth.fgov.be/standards/fhir/NamingSystem/bis",
                  "value":"66042620739"
               }

**Comment by FilipMigom** [comment]
At todays meeting, it was suggested to use "ssin"
"https://www.ehealth.fgov.be/standards/fhir/NamingSystem/ssin"

**Comment by bdc-ehealth** [comment]
bis and ssin use the same namingSystem: "https://www.ehealth.fgov.be/standards/fhir/NamingSystem/ssin". We do not create a new one.
