### ISSUE TITLE
Comment on the observation

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/hl7-be-fhir-laboratory-report#64]
We need to make the distinction between clinically relevant comments and technical comments

**Comment by FilipMigom** [comment]
Unclear how this can be handled within FHIR. Within HL7 V2 and the use of NTE, we could assign different NTE.4 (Comment Types). No mapping of this feature is available in HL7 FHIR. See also : https://confluence.hl7.org/pages/viewpage.action?pageId=40742730

**Comment by bdc-ehealth** [comment]
contact @costateixeira about this.

**Comment by costateixeira** [comment]
Based on https://build.fhir.org/ig/HL7/v2-to-fhir/ConceptMap-segment-nte-to-observation.html
I understand that we need to indeed add an extension. 

Extension is an extension on Annotation (because we can presume, also from the existence on HL7 v2 NTE.4) that this may be needed in other observations

```
Extension: BeAnnotationType
Id: be-ext-annotation-type
Title: "asdf"
Description: "sdfh"
* ^context[+].type = #element
* ^context[+].expression = "Annotation"
* value[x] only Coding
```

This needs to be added in the Labo Observation profile (in Observation.note) as
```
* note
  * extension contains BeAnnotationType named Type 0..*
```

**Comment by bdc-ehealth** [comment]
Dear,
 
Please find hereafter proposed resolutions for issies 64 and 65 – thanks José.
Please share any feedback on this approach. We will discuss next Tuesday in detail in the WG meeting.
 
 
	concerning Issue 64. 
I’ve discussed with other colleagues and here’s the proposed solution:
https://chat.fhir.org/#narrow/stream/179256-Orders-and.20Observation.20WG/topic/Observation.20comments
 
We can have a data type CodedAnnotation which is an extension from the Annotation. From then on, we can add “tags” to any of these annotations, wherever we use them.
I made the commit to show the solution – here’s the drill-down:
 
The Observation.note is no longer an Annotation but the new data type called BeCodedAnnotation
https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/branches/issue-64/StructureDefinition-be-observation-laboratory.html#tabs-diff
 
This BeCodedAnnotation is the same as Annotation but appended an extension called annotation-code
https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/branches/issue-64/StructureDefinition-coded-annotation.html#tabs-diff
 
The annotation-code is an extension defined as having a CodeableConcept
https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/branches/issue-64/StructureDefinition-annotation-code.html#tabs-diff 
 
This is bound by a valueset  - we need to define the values for those tags. We can do it anytime soon (or leave as is, because the binding is not required).
https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/branches/issue-64/ValueSet-be-vs-coded-annotation-types.html 
 
The way José sees it, this CodedAnnotation is a good enhancement to other Belgian profiles, and may be even accepted at the core FHIR spec globally, because there is interest and legacy for supporting it.
