### ISSUE TITLE
Comments on the reference range

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/hl7-be-fhir-laboratory-report#65]
We need a place to add a comment to the reference range (be it textual or numerical)

**Comment by FilipMigom** [comment]
See : https://www.hl7.org/fhir/observation-definitions.html and how we might use Observation.referenceRange.text

**Comment by bdc-ehealth** [comment]
contact @costateixeira about this.

**Comment by costateixeira** [comment]
We can add this extension on ReferenceRange:

```
Extension: BeReferenceRangeComment
Id: be-ext-referencerange-comment
Title: "asdf"
Description: "sdfh"
* ^context[+].type = #element
* ^context[+].expression = "Observation.referenceRange"
* value[x] only Annotation
```

This would be used as

```
* referenceRange
  * extension contains BeReferenceRangeComment named Comment 0..*
```

**Comment by bdc-ehealth** [comment]
	concerning Issue 65. 
 
The solution is simple after we have issue 64 resolved: We simply use the CodedAnnotation in the ReferenceRange (as an extension).
So we extend the element Observation.referenceRange to include an extension named BeReferenceRangeComment, which simply adds an element of type codedAnnotation  to referenceRange
https://build.fhir.org/ig/hl7-be/hl7-be-fhir-laboratory-report/branches/issue-65/StructureDefinition-be-observation-laboratory.html#tabs-diff
