### ISSUE TITLE
Alphanumeric referenceRange is not displayed

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/hl7-be-fhir-laboratory-report#67]

**Comment by LotteAd** [comment]
Example case:
https://github.com/hl7-be/hl7-be-fhir-laboratory-report/tree/master/testing/Macsys/815333045

**Comment by kjau** [comment]
Fix committed in https://github.com/ehealthplatformstandards/laboResultVisualization but I cannot assign the issue to me and close it :) (we should gather all Visualizer issues in de laboResultVisualization repository)

**Comment by LotteAd** [comment]
Issue made on visualiser github
