### ISSUE TITLE
Narrative empty?

### ISSUE THREAD

**Issue by bdc-ehealth** [hl7-be/hl7-be-fhir-laboratory-report#75]
At the moment we use "generated" narratives (see #32 and #45) . There has been a remark that the generated narrative should be able to be verified against the FHIR structure.

This lead to a discussion that resulted in a proposal  for "empty" narratives:

the main arguments were:
avoid inconsistence between generated narrative, FHIR structure and PDF.
avoid usage of the generated narrative by the GP software
the main source of debugging information should be the visualisation tool

If we need fallback information we should include the included PDF

**Comment by LotteAd** [comment]
This currently gives errors in the verificator:
![image](https://user-images.githubusercontent.com/93375157/149336225-c7e0d299-222f-4369-a800-0eb7173cd748.png)
