### ISSUE TITLE
Interpretation of observation: can we make a Belgian coding system?

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/hl7-be-fhir-laboratory-report#81]
For the moment we refer to the following coding system: http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation

However, for Belgian reports, we would like to suggest the use of a Belgian coding system which only allows the follow interpretations:
HH - H - N - L - LL.

**Comment by bdc-ehealth** [comment]
For microbiology, Thibault wants to add A - AA. Does the group agree?

**Comment by bdc-ehealth** [comment]
The group decides to add A and AA.
