### ISSUE TITLE
New interpretation coded set: how to correctly refer to the set?

### ISSUE THREAD

**Issue by LotteAd** [hl7-be/hl7-be-fhir-laboratory-report#94]
![image](https://user-images.githubusercontent.com/93375157/154054985-7d2df4e1-aa16-408d-840b-446e7a25674b.png)

See errors generated by Validator in printscreen above.

**Comment by bdc-ehealth** [comment]
@LotteAd Could you add the file that you were validating?

**Comment by LotteAd** [comment]
[815333044_Fhir.txt](https://github.com/hl7-be/hl7-be-fhir-laboratory-report/files/8069670/815333044_Fhir.txt)

I renamed it to a .txt-file because the reply doesn't support .json-files, but it was of course a .json-file that I uploaded :-)

**Comment by bdc-ehealth** [comment]
"interpretation": [
            {
                "coding": [
                    {
                        "system": "https://www.ehealth.fgov.be/standards/fhir/ValueSet/be-vs-observation-interpretation",
                        "code": "H"
                    }
                ]
            }
        ],

**Comment by LotteAd** [comment]
![image](https://user-images.githubusercontent.com/93375157/154080615-ade68218-6c2a-4b8a-b16d-bb94c5a33bdd.png)

Still get errors...

**Comment by bdc-ehealth** [comment]
"interpretation": [
{
"coding": [
{
"system": "http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation",
"code": "H"
}
]
}
],

**Comment by LotteAd** [comment]
Works like a charm!
