### ISSUE TITLE
Antibiotic result values

### ISSUE THREAD

**Issue by thibaultmh** [hl7-be/hl7-be-fhir-laboratory-report#97]
Hi,

Our lab system can have multiple values for the antibiotic results (RIS, MIC, ETEST, AGAR). Should these be expressed as multiple observations? I would create an observation for MIC, ETEST and AGAR (when available) and use the RIS as an interpretation.

If we have multiple observations, do we need to link these observations somehow? (I would assume with the 'observation.derivedFrom'?)

Finally, should we use dedicated LOINC codes for the MIC, ETEST and AGAR observations? Or can we use a general LOINC code for all observations. For example:

•	16-6  ( https://loinc.org/16-6/  : Amoxicillin [Susceptibility] by Minimum inhibitory concentration (MIC) )
•	6976-5 (https://loinc.org/6976-5/ : Amoxicillin [Susceptibility] by Gradient strip)
•	17-4 ( https://loinc.org/17-4/ : Amoxicillin [Susceptibility] by Disk diffusion (KB) )
•	18861-5 ( https://loinc.org/18861-5/ : Amoxicillin [Susceptibility] ) 

Can we just use 18861-5 for every observation? Currently our lab system only supports a single code per antibiotic result so it would be easier for us to use a single LOINC code for everything.

What are the workgroup's thoughts on this matter?

Best,
Thibault

**Comment by bdc-ehealth** [comment]
The WG decides that the most specific LOINC value as possible will be used. Add this to the guidance.
